using CarDealerShipBackend.Application.Interfaces;
using CarDealerShipBackend.Application.DTOs;
using CarDealerShipBackend.Infrastructure.Data;
using CarDealerShipBackend.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarDealerShipBackend.Infrastructure.Services
{
    public class SalesService : ISalesService
    {
        private readonly ApplicationDbContext _context;

        public SalesService(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<bool> ProcessPurchaseAsync(string userId, BuyCarRequest request)
        {
            // 1. Find the car
            var car = await _context.Cars.FindAsync(request.CarId);

            // Check if car exists and isn't already sold ('Y')
            if (car == null || car.IsSold == "Y")
                return false;

            // 2. Mark the car as sold
            car.IsSold = "Y";
            car.SoldDate = DateTime.Now;

            // 3. Create the Sales Contract
            var contract = new SalesContract
            {
                ContractNumber = "INV-" + Guid.NewGuid().ToString().Substring(0, 8).ToUpper(),
                CarId = car.CarId,
                // Handle the nullable decimal error by using ?? 0
                OriginalPrice = car.Price ?? 0,
                FinalPrice = request.FinalPrice,
                SaleDate = DateTime.Now,
                PaymentType = request.PaymentType,
                ContractStatus = "Active",
                // Link the customer using the User object found by ID
                Customer = await _context.Users.FirstOrDefaultAsync(u => u.Id == userId)
            };

            _context.SalesContracts.Add(contract);
            // Save changes here so the contract gets an ID generated by the DB
            await _context.SaveChangesAsync();

            // 4. If the user chose Installments, generate the payment schedule
            if (request.PaymentType == "Installments" && request.NumberOfInstallments.HasValue && request.NumberOfInstallments > 0)
            {
                decimal monthlyAmount = request.FinalPrice / request.NumberOfInstallments.Value;

                for (int i = 1; i <= request.NumberOfInstallments.Value; i++)
                {
                    var installment = new InstallmentPayment
                    {
                        ContractId = contract.ContractId, // Links to the contract we just saved
                        PaymentNumber = i,
                        ScheduledDate = DateTime.Now.AddMonths(i),
                        ScheduledAmount = monthlyAmount,
                        PaymentStatus = "Pending"
                    };
                    _context.InstallmentPayments.Add(installment);
                }
                await _context.SaveChangesAsync();
            }

            return true;
        }

        public async Task<IEnumerable<InstallmentResponse>> GetUserInstallmentsAsync(string userId)
        {
            // We use a manual JOIN because we don't want to change the InstallmentPayment entity
            var query = from installment in _context.InstallmentPayments
                        join contract in _context.SalesContracts
                        on installment.ContractId equals contract.ContractId
                        where contract.Customer.Id == userId
                        select new InstallmentResponse(
                            installment.PaymentId,
                            installment.ScheduledAmount,
                            installment.ScheduledDate,
                            installment.PaymentStatus ?? "Pending"
                        );

            return await query.ToListAsync();
        }
    }
}